resources:
  - type: compute.v1.instance
    name: minecraft
    properties:
      zone: us-east1-d
      machineType: https://www.googleapis.com/compute/v1/projects/craquelin-web/zones/us-east1-d/machineTypes/n1-standard-1
      disks:
        - deviceName: boot
          type: PERSISTENT
          boot: true
          autoDelete: true
          initializeParams:
            sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9
      networkInterfaces:
        - network: https://www.googleapis.com/compute/v1/projects/craquelin-web/global/networks/default
          accessConfigs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
      metadata:
        items:
          - key: startup-script
            value: 
              echo Minecraft installation starting
              sudo apt-get update
              echo Updating JRE
              sudo apt-get install -y default-jre-headless
              sudo mkdir -p /home/minecraft
              cd /home/minecraft
              sudo su
              echo Downloading Minecraft configs
              gsutil cp gs://craquelin-web.appspot.com/minecraftconfigs/eula.txt eula.txt
              gsutil cp gs://craquelin-web.appspot.com/minecraftconfigs/server.properties server.properties
              curl https://launcher.mojang.com/v1/objects/6f27430bcd9b06d3dcb5d2966c75d5e491915c9c/server.jar > server.jar
              echo Starting server
              java -Xms1G -Xmx3G -d64 -jar server.jar nogui
              