resources:
  - type: compute.v1.instance
    name: minecraft
    properties:
      zone: us-east1-d
      machineType: https://www.googleapis.com/compute/v1/projects/craquelin-web/zones/us-east1-d/machineTypes/n1-standard-1
      disks:
        - deviceName: boot
          type: PERSISTENT
          boot: true
          autoDelete: true
          initializeParams:
            sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9
      networkInterfaces:
        - network: https://www.googleapis.com/compute/v1/projects/craquelin-web/global/networks/default
          accessConfigs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
      metadata:
        items:
          - key: startup-script-url
            value: gs://craquelin-web.appspot.com/start.sh
    accessControl:
      gcIamPolicy:
        bindings:
        - role: roles/storage.admin
          members:
          - "666757427670-compute@developer.gserviceaccount.com"
              