resources:
  - type: compute.v1.instance
    name: minecraft
    properties:
      zone: us-east1-d
      machineType: https://www.googleapis.com/compute/v1/projects/craquelin-web/zones/us-east1-d/machineTypes/n1-standard-2
      disks:
        - deviceName: boot
          type: PERSISTENT
          boot: true
          autoDelete: true
          initializeParams:
            sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9
      networkInterfaces:
        - network: https://www.googleapis.com/compute/v1/projects/craquelin-web/global/networks/default
          accessConfigs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
      tags:
        items:
          - minecraft
      metadata:
        items:
          - key: startup-script-url
            value: gs://craquelin-web.appspot.com/start.sh
      serviceAccounts:
        - email: default
          scopes:
            - https://www.googleapis.com/auth/devstorage.read_only
